# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVHn5zGVk06CTwXRZQN_2J9KwEULCnTS
"""

#Hourglass problem is little complicate to understand and to code at first , but
# as we understand this problem it is as easy to code 


# hour glass can be of anysize (more than 3x3)

# so first of all go and search what hourglass looks like, it will give more
# clear picture of this problem

#  we have to extract all the possible hourglasses from the input

# hourglass is of the shape,
#  a b c      eg  1 1 2    2 4 1
#    d              4        0 
#  e f g          0 0 1    2 1 0

arr = [[1,1,2,3,0,0],
       [2,4,1,2,1,0],
       [0,0,1,1,0,1],
       [2,1,0,0,1,2],
       [1,1,1,1,1,1],
       [2,0,0,0,0,1]]   # from this 6x6 input 4x4=16 hourglass can be possible

def add(a,b,c,d,e,f,g):
  return a+b+c+d+e+f+g  # check this later, its just the add function

addition = []           

for x in range(4):      # we took range(4) cause during calculation we r going 
  for y in range(4):    # to add 1 or 2 as per requirement to access input

    a = arr[x][y]      #    this is HOURGLASS 
    b = arr[x][y+1]    # a= u[x][y]     b= u[x][y+1]      c= u[x][y+2]
    c = arr[x][y+2]    #               d= u[x+1][y+1]
    d = arr[x+1][y+1]  # e= u[x+2][y]  f= u[x+2][y+1]     g= u[x][y+2]
    e = arr[x+2][y]
    f = arr[x+2][y+1]
    g = arr[x+2][y+2]

    print(a, b, c)
    print('  ', d, '  ')
    print(e, f, g)

    print()                # sum of hourglass
    s = add(a,b,c,d,e,f,g)
    print(s)

    addition.append(s)     # appending sum value of each hourglass in list
    
    print()
  print()
  print()

print(max(addition))      #main output(ans): max of the hourglass
===========================================================================================================================================

==========================================SAME CODE JUST REMOVED ADDITIONAL PRINT() funcs.===================================================
arr = [[1,1,2,3,0,0],
       [2,4,1,2,1,0],
       [0,0,1,1,0,1],
       [2,1,0,0,1,2],
       [1,1,1,1,1,1],
       [2,0,0,0,0,1]]

def add(a,b,c,d,e,f,g):
  return a+b+c+d+e+f+g

addition = []
for x in range(4):
  for y in range(4):                # removing all additional things

    a = arr[x][y]
    b = arr[x][y+1]                 # max of hourglasses from Input given
    c = arr[x][y+2]
    d = arr[x+1][y+1]
    e = arr[x+2][y]
    f = arr[x+2][y+1]
    g = arr[x+2][y+2]
    
    s = add(a,b,c,d,e,f,g)

    addition.append(s)
    
print(max(addition))
